apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-k8-scg
spec:
  portal:
    capacity: 3
    reserved: 1
    expires: 90m
    orphaned: 5m
  workshops:
  - name: lab-k8-scg
