apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: helloworld-route-config
spec:
  service:
    name: helloworld
  routes:
    - predicates:
        - Path=/helloworld/**
      filters:
        - StripPrefix=1
